### ISSUE TITLE
Bridge -1- Link the Python Math with a Python radar

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_cityscopeJS_UI#11]
Hi @lisaorii,

Congrats for the link between the Math and the excel Radar. Next step is to have a visual "real time" Output of the Radar in Python, so we can test visually the module without the need of connecting it with the Front end

**Comment by lisaorii** [comment]
Hi @LAAP 

I wrote a Python script that allows the maths to generate a radar chart. The values are random right now, but the chart will look different depending on the static data that is inputted. I will create a pull request for this code.

http://127.0.0.1:50074/
<img width="1341" alt="Screen Shot 2020-01-22 at 3 20 17 PM" src="https://user-images.githubusercontent.com/42143938/72930815-c7e7cf00-3d2a-11ea-9452-6be8b71d65be.png">

**Comment by LAAP** [comment]
Thank you @lisaorii,
