### ISSUE TITLE
Validation of the Math

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_cityscopeJS_UI#7]
Hi @lisaorii 

This is great! As a next step maybe we can validate the Math by comparing with an excel file

**Comment by lisaorii** [comment]
Hi @LAAP 
Maths has been validated - the script's calculations are accurate!

**Comment by LAAP** [comment]
Awesome, 
Please can you document that in the "Wiki"? a very simple entrance explaining the quick validation may help in the future.
Thank you very much!

**Comment by lisaorii** [comment]
Done! Hopefully I created the Wiki correctly. Please let me know if there is an issue.

**Comment by LAAP** [comment]
OK, Perfect! Thank you very much!
