### ISSUE TITLE
Visualization of a simple 3 axes Radar Chart

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_cityscopeJS_UI#8]
Dear @lisaorii,

As we have commented, Please, can you make as an output of the Python script a Visualization of a simple 3 axes Radar Chart?

Example:
[https://image.slidesharecdn.com/radarchartstype-110405002000-phpapp01/95/radar-chart-type-in-powerpoint-3-728.jpg?cb=1301962833](url)

Thanks!

**Comment by lisaorii** [comment]
Hi @LAAP 

There seems to be an issue with the Example link you sent me. Could you send it again?
Also, by '3 axes' do you mean Density, Diversity, Proximity right? However, Proximity is not ready yet so I think the first version of the visualization will be '2 axes' if that is ok.

Thank you!

**Comment by LAAP** [comment]
Hi  @lisaorii,

Yes, the link is not well embedded in the Github, however you can just copy-paste it in google and get the image.

Please Keep the 3 axes (Minimum axes for a radar chart) "Density, Diversity, Proximity". Proximity can stay in "0". No worries about that.

Thanks!

**Comment by lisaorii** [comment]
HI @LAAP 

Here is a simple 3 axes radar chart for Employment and Residential. It has also been added to the RADAR branch where I created a pull request.

![radarchart_v1](https://user-images.githubusercontent.com/42143938/72555088-f0268800-3869-11ea-9470-c0a3c1eed106.png)

**Comment by LAAP** [comment]
Awesome Lisa! This is Fantastic!
